# Generated by Django 4.2.6 on 2023-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('actualizacionUsuario', models.IntegerField(null=True)),
                ('creacionFechaHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizacionFechaHora', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
