# Generated by Django 4.2.6 on 2023-11-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0002_fabricante_alter_proveedor_actualizacionusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('unidadMedida', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB'), ('TB', 'TB'), ('PB', 'PB')], default='TB', max_length=2)),
                ('actualizacionUsuario', models.IntegerField(blank=True, null=True)),
                ('creacionFechaHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizacionFechaHora', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
