# Generated by Django 4.2.6 on 2023-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0003_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
