# Generated by Django 4.2.6 on 2023-11-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0005_historialcompras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialcompras',
            old_name='fechaCompa',
            new_name='fechaCompra',
        ),
    ]
