# Generated by Django 4.2.6 on 2023-11-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0006_rename_fechacompa_historialcompras_fechacompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialcompras',
            old_name='proveedorId',
            new_name='proveedor',
        ),
    ]
