# Generated by Django 4.2.6 on 2023-11-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0007_rename_proveedorid_historialcompras_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialCompras',
        ),
    ]
