# Generated by Django 4.2.6 on 2023-11-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0009_historialcompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=12)),
                ('anioLanzamiento', models.IntegerField(null=True)),
                ('garantiaAnios', models.IntegerField(null=True)),
                ('cantidadBahiasInternas', models.IntegerField(null=True)),
                ('cantidadUnidadesExpansion', models.IntegerField(null=True)),
                ('maxCantDiscosUnidadExpansion', models.IntegerField(null=True)),
                ('ramIncluidaGB', models.IntegerField(null=True)),
                ('ramMax', models.IntegerField(null=True)),
                ('ramSlots', models.IntegerField(null=True)),
                ('cantidadNics1Gb', models.IntegerField(null=True)),
                ('cantidadNics10Gb', models.IntegerField(null=True)),
                ('cantidadBahiasPci', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('esRackeable', models.BooleanField(default=False)),
                ('tieneFuentePoderRedundante', models.BooleanField(default=False)),
                ('actualizacionUsuario', models.IntegerField(blank=True, null=True)),
                ('creacionFechaHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizacionFechaHora', models.DateTimeField(auto_now=True, null=True)),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlHardware.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='discoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloCorto', models.CharField(max_length=20, verbose_name='Modelo Comercial')),
                ('modeloLargo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Código del Modelo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('esSSD', models.BooleanField(default=False, verbose_name='Es SSD?')),
                ('aniosGarantia', models.IntegerField(default=1, verbose_name='Años de Garantía')),
                ('rpms', models.IntegerField(null=True, verbose_name='RPMs')),
                ('cacheEnMB', models.IntegerField(verbose_name='Cache en MB')),
                ('actualizacionUsuario', models.IntegerField(blank=True, null=True)),
                ('creacionFechaHora', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizacionFechaHora', models.DateTimeField(auto_now=True, null=True)),
                ('capacidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlHardware.capacidad')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlHardware.fabricante')),
            ],
        ),
    ]
