# Generated by Django 4.2.6 on 2023-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlHardware', '0010_nasmodelo_discomodelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discomodelo',
            name='aniosGarantia',
        ),
        migrations.AddField(
            model_name='discomodelo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discomodelo',
            name='garantiaAnios',
            field=models.IntegerField(choices=[(1, 1), (3, 3), (5, 5)], default=1, verbose_name='Años de Garantía'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='anioLanzamiento',
            field=models.IntegerField(null=True, verbose_name='Año Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='cantidadBahiasInternas',
            field=models.IntegerField(blank=True, default=1, verbose_name='Número Bahías Internas'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='cantidadBahiasPci',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ranuras PCI Express'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='cantidadNics10Gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adaptadores Red de 10 Gbps'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='cantidadNics1Gb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adaptadores Red de 1 Gbps'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='cantidadUnidadesExpansion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Unidades de Expanasión'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='esRackeable',
            field=models.BooleanField(default=False, verbose_name='Unidad de Rack'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='garantiaAnios',
            field=models.IntegerField(choices=[(1, 1), (3, 3), (5, 5)], default=1, verbose_name='Años de Garantía'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='maxCantDiscosUnidadExpansion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discos por Unidad Expansión'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='ramIncluidaGB',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAM Incluída (GB)'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='ramMax',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAM Máxima (GB)'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='ramSlots',
            field=models.IntegerField(null=True, verbose_name='Ranuras para RAM'),
        ),
        migrations.AlterField(
            model_name='nasmodelo',
            name='tieneFuentePoderRedundante',
            field=models.BooleanField(default=False, verbose_name='Unidad con fuente de poder redundante'),
        ),
    ]
